
# This is an environment file for conda to set up a Python environment for Suite2P.
# It includes necessary packages and their versions, ensuring compatibility with Suite2P, installs most scientific packages and dependencies.
# It also installs, the hdf5io package for handling HDF5 files.

#Under pip:, we install:

#    suite2p[gui] — GUI version
#    hdf5io for the mesc part

#to install the environment:
#    conda env create -f environment.yml
#    conda activate suite2p



name: suite2p
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.26.4
  - matplotlib
  - tables>=3.7.0
  - tifftools
  - pyqt=5.15.*
  - scipy
  - scikit-learn
  - opencv
  - pip
  - pip:
      - suite2p[gui]
      - git+https://github.com/hillierdani/hdf5io.git


