site_name: HeureCa
site_url: https://nszti.github.io/hstim_pipeline/
use_directory_urls: false
theme:
    name: material
    custom_dir: overrides
    palette:
        scheme: default
        primary: black
        accent: green
    features:
        - navigation.tabs
        - toggle
        - content.code.copy
nav:
    - Home: index.md
    - Setup:
          - Overview: setup/usage.md
          - Interpreter Setup: setup/interpreter.md
          - MATLAB Integration: setup/matlab_integration.md
          - Help to avoid errors: setup/help.md
    - Documentation:
          - Structure: documentation/structure.md
          - Functions: documentation/api.md
          - Examples: documentation/runs.md
plugins:
    - search
extra_css:
  - stylesheets/custom.css